apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-db
  name: todo-db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - image: mysql:5.7
          name: todo-db
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: todo_app
            - name: MYSQL_USER
              value: todo_user
            - name: MYSQL_PASSWORD
              value: password
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-db
  name: todo-db
spec:
  ports:
    - port: 3306
  selector:
    app: todo-db
  clusterIP: None