apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - image: lordrahl/todo-app
          name: todo-app
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  ports:
    - port: 3000
      nodePort: 30250
      protocol: TCP
      targetPort: 3000
  selector:
    app: todo-app
  type: NodePort
  sessionAffinity: None